## AWS Buildspec file for Codebuild/Code*
## https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
##

# THIS SHOULD BE BUILT IN THE SAME NODE VERSION + ARCHITECTURE THAT LAMBDA USES AND LOCAL USES, nodejs 18 + arm

version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - n 18.13.0
  pre_build:
    on-failure: ABORT
    commands:
      - yarn install
  build:
    on-failure: ABORT
    commands:
      # something else here to bake in sha and maybe something for datadog too?
      - NITRO_PRESET=aws-lambda yarn build
  post_build:
    on-failure: ABORT
    commands:
      - cd .output && zip -r ../output.zip * && cd ..
      # - NEW_VERSION=$(aws lambda update-function-code --profile sandbox --region us-west-2 --function-name aravn-nuxt-test --zip-file fileb://./output.zip --publish --architectures arm64 --query 'Version' | tr -d '"')
      # - aws lambda update-alias --profile sandbox --region us-west-2 --function-name aravn-nuxt-test --name aravn-nuxt-test --function-version $NEW_VERSION
      - NEW_VERSION=$(aws lambda update-function-code --function-name aravn-nuxt-test --zip-file fileb://./output.zip --publish --architectures arm64 --query 'Version' | tr -d '"')
      - aws lambda update-alias --function-name aravn-nuxt-test --name aravn-nuxt-test --function-version $NEW_VERSION
artifacts:
  files:
    - '**/*'
  base-directory: .output
  name: shn/output.zip
  
